# Generated by Django 4.0.3 on 2023-10-08 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_otpmodel_orderplaced_datetime_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 18, 28, 59, 128450, tzinfo=utc)),
        ),
    ]
