# Generated by Django 4.0.3 on 2023-10-21 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_productinorderplaced_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='datetime_of_payment',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 10, 9, 20, 593662, tzinfo=utc)),
        ),
    ]
