# Generated by Django 4.0.3 on 2023-10-21 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_otpmodel_expiry_payment_orderplaced_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 20, 32, 42, 988696, tzinfo=utc)),
        ),
    ]
