# Generated by Django 4.0.3 on 2023-10-22 04:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_otpmodel_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 4, 25, 2, 72067, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ProductInOrderPlaced',
        ),
    ]
