# Generated by Django 4.0.3 on 2023-11-04 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_orderplaced_datetime_of_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='datetime_of_payment',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 22, 34, 57, 49758, tzinfo=utc)),
        ),
    ]
